apiVersion: v1
kind: PersistentVolume
metadata:
    name: logging-pv
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteOnce
    storageClassName: logging-pv
    persistentVolumeReclaimPolicy: Recycle
    nfs:
        path: /mnt/data/pv
        server: 10.104.61.249
