apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: logging-pvc
    namespace: kube-system
spec:
    storageClassName: logging-pv
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
